version: "3"

services:
  tasks_api:
    image: tasks_api
    build: .
    ports:
      - "5000:5000"
    command: /bin/sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 --workers 2 --threads 4 run:app"

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - tasks_api
