version: "3"

services:
  tasks_api:
    image: tasks_api
    build: .
    ports:
      - "5000:5000"
    command: /bin/sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 run:app"

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - tasks_api
