version: "3"

services:
  tango_api:
    image: tango_api
    build: .
    ports:
      - "5000:5000"
    command: /bin/sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 app:app"

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - tango_api
