version: "3"

services:
  tango_api:
    image: tango_api
    build: .
    ports:
      - "5000:5000"

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - tango_api
