"""empty message

Revision ID: 360040257725
Revises: a81df4a39177
Create Date: 2025-04-28 09:36:35.197674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '360040257725'
down_revision = 'a81df4a39177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('recurring_pattern')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_pattern', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
