"""Add due_date to subtasks

Revision ID: d73d5fd1acc4
Revises: ddbef77f3bc4
Create Date: 2025-04-27 22:17:41.821830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73d5fd1acc4'
down_revision = 'ddbef77f3bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
